### ISSUE TITLE
Object TPM_A1 (ID 0x02FF) makes app crash

### ISSUE THREAD

**Issue by gus8313** [rnd-ash/MBUX-Port#1]
Hello,
When calling object TPM_A1 (from Can bus B of 203 C-Class), application always crash.
For example, adding TPM_A1.toString() to display tire pressure monitoring data makes app crash when opening display
Issue does not occur when calling other objects like EZS_A6

**Comment by rnd-ash** [comment]
This is to be expected under some circumstances....

The code crashes at the following point:
```Kotlin
/** Gets Tire pressure front left  **/
	fun get_tirepress_fl() : TIREPRESS_FL = when(CanBusNative.getECUParameterB(CanBAddrs.TPM_A1, 24, 8)) {
		 254 -> TIREPRESS_FL.NO_IND
		 255 -> TIREPRESS_FL.SNA
		 else -> throw Exception("Invalid raw value for TIREPRESS_FL")
	}
```

You need to wrap the call in a try/catch block to be safe.

What is happening here is that if your car has no TP system installed, or the headunit has not yet received a TPM_A1 frame from canbus, then getting any value from this frame will return '0'. And since that is not 254 or 255, it throws an Exception, causing the application to crash

**Comment by gus8313** [comment]
Works now, many thanks !
